/*Database objects create statements: create table, foreign keys, indexes, etc.*/

--CREATING TABLE PROJECT1_BOOK
CREATE TABLE PROJECT1_BOOK (
    ISBN VARCHAR2(4000) PRIMARY KEY,
    TITLE VARCHAR2(4000)
);

--CREATING TABLE PROJECT1_BOOK_AUTHORS
CREATE TABLE PROJECT1_BOOK_AUTHORS (
    AUTHOR_ID NUMBER(38) NOT NULL,
    ISBN VARCHAR2(4000) NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES PROJECT1_AUTHORS(AUTHOR_ID),
    FOREIGN KEY (ISBN) REFERENCES PROJECT1_BOOK(ISBN)
);

--CREATING TABLE PROJECT1_AUTHORS
CREATE TABLE PROJECT1_AUTHORS (
    AUTHOR_ID INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR2(4000),
    PRIMARY KEY(AUTHOR_ID)
);

--CREATING TABLE PROJECT1_LIBRARY_BRANCH
CREATE TABLE PROJECT1_LIBRARY_BRANCH(
    BRANCH_ID INT PRIMARY KEY,
    BRANCH_NAME VARCHAR2(4000),
    ADDRESS VARCHAR2(4000)
);

--CREATING TABLE PROJECT1_BOOK_COPIES
CREATE TABLE PROJECT1_BOOK_COPIES (
    BOOK_ID INT GENERATED ALWAYS AS IDENTITY,
    ISBN VARCHAR2(4000) NOT NULL,
    BRANCH_ID INT NOT NULL,
    FOREIGN KEY (ISBN) REFERENCES PROJECT1_BOOK (ISBN),
    FOREIGN KEY (BRANCH_ID) REFERENCES PROJECT1_LIBRARY_BRANCH (BRANCH_ID),
    PRIMARY KEY(BOOK_ID)
);

--CREATING TABLE PROJECT1_BORROWE
CREATE TABLE PROJECT1_BORROWER(
    CARD_NO VARCHAR2(4000) PRIMARY KEY,
    SSN VARCHAR2(4000) DEFAULT NULL,
    FNAME VARCHAR2(4000) DEFAULT NULL,
    LNAME VARCHAR2(4000) DEFAULT NULL,
    ADDRESS VARCHAR2(4000) DEFAULT NULL,
    PHONE VARCHAR2(4000) DEFAULT NULL
);

--CREATING TABLE PROJECT1_BOOK_LOANS
CREATE TABLE PROJECT1_BOOK_LOANS(
    LOAN_ID INT GENERATED ALWAYS AS IDENTITY,
    BOOK_ID INT NOT NULL,
    CARD_NO VARCHAR2(4000) NOT NULL,
    DATE_OUT DATE DEFAULT NULL,
    DUE_DATE DATE DEFAULT NULL,
    DATE_IN DATE DEFAULT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES PROJECT1_BOOK_COPIES(BOOK_ID),
    FOREIGN KEY (CARD_NO) REFERENCES PROJECT1_BORROWER(CARD_NO),
    PRIMARY KEY (LOAN_ID)
);

--CREATING TABLE PROJECT1_FINES
CREATE TABLE PROJECT1_FINES(
    LOAN_ID INT PRIMARY KEY,
    FINE_AMT FLOAT DEFAULT NULL,
    PAID FLOAT DEFAULT NULL,
    FOREIGN KEY (LOAN_ID) REFERENCES PROJECT1_BOOK_LOANS(LOAN_ID)
);
