/*SQL to find the city wise monthly fine.*/

SELECT
    B.CITY,
    SUM(F.FINE_AMT)  AS MONTHLY_TOTAL_FINE,
    TO_CHAR(TO_DATE(EXTRACT(MONTH FROM BL.DATE_IN), 'MM'), 'MONTH') AS MONTH_NAME
FROM
    PROJECT1_BOOK_LOANS BL
    INNER JOIN PROJECT1_FINES F ON BL.LOAN_ID = F.LOAN_ID
    INNER JOIN PROJECT1_BORROWER B ON B.CARD_NO = BL.CARD_NO
GROUP BY
    CITY,
    TO_CHAR(TO_DATE(EXTRACT(MONTH FROM BL.DATE_IN),'MM'),'MONTH');

/* SQL to find the total fine amount for each borrower*/

--TOTAL FINE AMOUNT FOR EACH BORROWER--
SELECT
    B.FNAME,
    B.LNAME,
    TEMP.TOTAL_FINE_AMOUNT
FROM
    (
        SELECT
            BL.CARD_NO,
            SUM(F.FINE_AMT) AS TOTAL_FINE_AMOUNT
        FROM
            PROJECT1_BOOK_LOANS BL
            INNER JOIN PROJECT1_FINES F ON BL.LOAN_ID = F.LOAN_ID
        GROUP BY
            BL.CARD_NO
    ) TEMP
    INNER JOIN PROJECT1_BORROWER B ON TEMP.CARD_NO = B.CARD_NO 
    ORDER BY FNAME;

/*SQL to find which city has maximum fine in the month of November.*/

SELECT
    TEMP.CITY,
    TEMP.MONTHLY_TOTAL_FINE
FROM
    (
        SELECT
            B.CITY,
            SUM(F.FINE_AMT)  AS MONTHLY_TOTAL_FINE,
            EXTRACT (MONTH FROM DATE_IN) AS MONTH_NAME
        FROM
            PROJECT1_BOOK_LOANS BL
            INNER JOIN PROJECT1_FINES    F ON BL.LOAN_ID = F.LOAN_ID
            INNER JOIN PROJECT1_BORROWER B ON B.CARD_NO = BL.CARD_NO
        WHERE
            EXTRACT (MONTH FROM DATE_IN) = 11
        GROUP BY
            CITY,
            EXTRACT (MONTH FROM DATE_IN)
    ) TEMP 
    ORDER BY TEMP.MONTHLY_TOTAL_FINE DESC
    FETCH FIRST 1 ROW ONLY;
